### ISSUE TITLE
TODO: multi workspace

### ISSUE THREAD

**Issue by ZhongYic00** [linuxdeepin/treeland#184]
```[tasklist]
### Tasks
- [x] multi workspace static display
- [x] workspace add/remove, window move to workspace
- [x] winswitcher & multitaskView model filter by workspace
- [x] multitaskView layout partial update => relayout animation
- [x] multitaskView add workspace chooser
- [ ] workspace switch animation
- [x] drag interaction
- [x] drag animation
- [x] adapt dockpreview
```

**Comment by ZhongYic00** [comment]
Model design
- surfaces model
	- group by workspace id=>workspace model
	- qobjparent repeater
		- workspaceId update=>trigger reparent
	- group by workspace id=>workspace model, or workspaceItem children list
		- filter surface type => multitaskview model, switcher model
			- group by output => per output model
				- eqh-grid layout

**Comment by ZhongYic00** [comment]
Model design revised
workspace:
- wsid: uniq static
- wsRelId: dynamic, pos in layout

- workspace manager
  - workspace layoutOrder model
    - repeater, assign relative index to workspaces
      - ToplevelContainer
        - surfaces model
          - multitaskview
            - filter by output
              - eqh-grid layout
          - winswitcher
  - workspacesById
    - wsid to toplevelContainer

issues:
- behavior of stack order across workspaces
  -  `总在当前工作区`
  - move between workspaces
  - move due to destruction

**Comment by ZhongYic00** [comment]
MultitaskView design
- repeater, for each workspace
  - repeater, for each output
- animation item
  - repeater, for each output,
    - infListView, for workspaces' window grid
